name: Creating a pull request

on:
   push:
     branches:
       - main
       - deploy
       - 'feature/**'

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
      
      -  name: Checkout code
         uses: actions/checkout@v3

      -  name: Configure JDK 11
         uses: actions/setup-java@v3
         with:
            java-version: '11'
            distribution: temurin
            cache: maven

      -  name: Run tests
         run: |
            mvn clean package -DskipTests
            mvn test -Dworkflow=Github
