name: Deploy artifacts to Maven Central

on:
   push:
     branches:
       - main
       - deploy
       - 'feature/**'

jobs:
   deploy:
      runs-on: ubuntu-latest

      steps:
      
      -  name: Checkout code
         uses: actions/checkout@v3

      -  name: Configure JDK 11
         uses: actions/setup-java@v3
         with:
            java-version: '11'
            distribution: temurin
            cache: maven

      -  name: Import GPG key
         env:
            GPG_PRIVATE_KEY: ${{ secrets.GPG_PRIVATE_KEY }}
            GPG_PASSPHRASE: ${{ secrets.GPG_PASSPHRASE }}
         run: |
            echo "$GPG_PRIVATE_KEY" | gpg --batch --import
            echo "default-key $(gpg --list-keys --with-colons | grep pub | head -n 1 | cut -d':' -f5)" > ~/.gnupg/gpg.conf
            echo "pinentry-mode loopback" >> ~/.gnupg/gpg.conf

      -  name: Setup Maven Settings
         run: |
            mkdir -p ~/.m2
            echo "<settings>
                     <servers>
                        <server>
                            <id>central</id>
                            <username>${{ secrets.OSSRH_USERNAME }}</username>
                            <password>${{ secrets.OSSRH_PASSWORD }}</password>
                        </server>
                     </servers>
                     <profiles>
                        <profile>
                           <id>central</id>
                           <activation>
                              <activeByDefault>true</activeByDefault>
                           </activation>
                           <properties>
                              <gpg.executable>gpg</gpg.executable>
                              <gpg.passphrase>${{ secrets.GPG_PASSPHRASE }}</gpg.passphrase>
                           </properties>
                        </profile>
                     </profiles>
                  </settings>" > ~/.m2/settings.xml

      -  name: Deploy to Maven Central
         run: mvn clean deploy -P release --settings ~/.m2/settings.xml -DskipTests
